Change Gcc error regex Not sure what (\[(?P<msg1>.*)\]) is for but if it isn't required, the space separating it from (?P<msg>.*) also shouldn't be required (as demonstrated from a couple examples):
All of these are not caught with the previous regex and are caught with this modification (only the first line of the error message is included):
`src/efi.h:374:5: error: unknown type name 'EFI_SIMPLE_INPUT_MODE'; did you mean 'EFI_SIMPLE_POINTER_MODE'?`
`src/efi.h:420:8: error: expected ';', ',' or ')' before 'UINT32'`
`src/efi.c:374:5: error: called object is not a function or function pointer`